/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author edgar
 */
public class VistaFinal extends javax.swing.JFrame {
    String ruta1="src/fondos/fondo.gif";
    String ruta2="src/fondos/lose.gif";
    String ruta3="src/fondos/over.gif";
    String ruta4="src/fondos/you win.gif";

    public VistaFinal(int moneda) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (moneda !=0) {
            imagenFin(ruta1, fondo);
            imagenFin(ruta4, Fon);
        }else{
            imagenFin(ruta2, fondo);
            imagenFin(ruta3, Fon);
        
        
        }

    }

    public void imagenFin(String ruta,JLabel fondo) {

        
            ImageIcon ds = new ImageIcon(ruta);
            Icon isd = new ImageIcon(ds.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
            fondo.setIcon(isd);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fon = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Fon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 260, 100));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fon;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
