/*
 * Uversidad Central del Ecuador 
 * Facultad de Ingenieria y CIencias aplicadas
 * Ingenieria en Sistemas de Informacion
 * Algoritmos
 * Grupo 9 
 * Integrantes: 
 *       - Bolaños Josue
 *       - Espinosa David
 *       - Teran Edgar
 * Este es un juego que implementa el algoritmo del camino mas corto
 */

package vistas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Grupo 9
 */
public class VistaInicial extends javax.swing.JFrame {

   
    public VistaInicial() {
        initComponents();
        this.setIconImage(new ImageIcon("src/fondos/logo.png").getImage() );
        jPanel2.setBackground(new Color(0, 179, 71, 90));
        setLocationRelativeTo(null);
        ImageIcon d = new ImageIcon("src/fondos/logo.png");
        Icon id = new ImageIcon(d.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(id);
        ImageIcon de = new ImageIcon("src/fondos/Pueblo.gif");
        Icon idd = new ImageIcon(de.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_DEFAULT));
        jLabel3.setIcon(idd);
    }

    public void progres() {
//        IngresoUsuario iniciar = new IngresoUsuario();
        VistaIngresoNombre m = new VistaIngresoNombre();
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(90);
                
                progreso.setText(Integer.toString(i) + "%");
                barra.setValue(i);
                if (i == 100) {
//                    musica.ReproducirSonido("src/musica/juego-de-tronos-2.wav");
//                    clip.stop();
                    this.dispose();                   
                    m.setVisible(true);
                                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progreso = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progreso.setBackground(new java.awt.Color(102, 102, 102));
        progreso.setForeground(new java.awt.Color(255, 255, 255));
        progreso.setText("1%");
        getContentPane().add(progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 330, 240));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 340));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar barra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel progreso;
    // End of variables declaration//GEN-END:variables
}
